### ISSUE TITLE
paho-mqtt recipe failed

### ISSUE THREAD

**Issue by js333031** [solettaproject/meta-soletta#90]
I'm using the generic Yocto instructions for Edison.  Fetch task during paho mqtt fails. 

I modified poky/meta-intel-iot-middleware/recipes-connectivity/paho-mqtt/paho-mqtt_3.1.bb

Lines 14-16 are the original. Lines 17-18 are my modifications to get past the fetch error.

   14 #SRC_URI = "git://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.c.git;protocol=http \
   15 #           file://makefile.patch \
   16 #"
   17 SRC_URI = "git://github.com/eclipse/paho.mqtt.c.git;protocol=http \  
   18             file://makefile.patch \
   19 "

**Comment by brunobottazzini** [comment]
@js333031, could you please pass us all the layers you are including and its hash ? For the issues you've opned are the hashs all the same ?

For example:

```
meta-yocto-bsp    = "master:c7e614c438706fb3ed7520b4990ebb3973366942"
meta-soletta      = "master:b0ffb70b8ca895ef721aafa07a99b228fb06a434"
meta-oe           = "master:7be16bce816dee5e9ea1dd241b5a3543fdf78356"
meta-intel-iot-middleware = "master:821cf14c8304669d9ce0c5b87b9be5a6eecff6e5"
meta-intel        = "master:d9727db3e7957d4842e4afeeeaa6420d5d2cfa7d"
```

**Comment by js333031** [comment]
I followed the instructions here:
https://github.com/solettaproject/soletta/wiki/Creating-an-Edison-Image-with-Yocto

I will retry and provide the hashs.

**Comment by js333031** [comment]
Build Configuration:
BB_VERSION        = "1.24.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-12.04"
TARGET_SYS        = "i586-poky-linux"
MACHINE           = "edison"
DISTRO            = "poky-edison"
DISTRO_VERSION    = "1.7.2"
TUNE_FEATURES     = "m32 core2"
TARGET_FPU        = ""
meta  
meta-yocto  
meta-yocto-bsp    = "(HEADdetachedatyocto-1.7.2):29812e61736a95f1de64b3e9ebbb9c646ebd28dd"
meta-intel-edison-bsp 
meta-intel-edison-distro = "master:6ad94a4c2372bb817822b751f1767ff66bd643c8"
meta-intel-iot-middleware = "(HEADdetachedatc6d6814):c6d681475e76107e6c04c5f7a06034dc9e772d1e"
meta-intel-arduino = "master:6ad94a4c2372bb817822b751f1767ff66bd643c8"
meta-arduino      = "1.6.x:541b127163acb243109f07141bf249da2ecdcd9a"
meta-soletta      = "master:35c2902781a394aa14ba8e9b5a1738facce195cf"

**Comment by brunobottazzini** [comment]
@js333031, 

This error is from a recipe that comes from meta-intel-edison and it is not from meta-soletta.

To get the best solution for this problem, you should send an e-mail to the meta-intel-edison mailing list so the maintainers can help you out. 

Link: https://layers.openembedded.org/layerindex/branch/master/layer/meta-intel-edison-bsp/

In any case:

I replicated the problem here and the URL that yocto downloads the repository does not exist anymore.

I could partially workaround it by changing the SRC_URI inside of the file paho-mqtt_3.1.bb 

from:

```
git://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.c.git
```

to

```
https://github.com/eclipse/paho.mqtt.c
```

Adding the CHECK SUMS:

```
SRC_URI[md5sum] = "82799eb3e2393f7c430b6158c721ee76"
SRC_URI[sha256sum] = "2c5eb725828d14bf8980b5a6393a84019432686cb2ea4d99335a1c39bfd6c624"
```

We have to change some patches here that I did not test it. You can also remove the recipe if you are not going to use it anyway.

Best Regards,
